name = "Cairn"
uuid = "f102e12b-bead-4d20-9368-b11e50e649cd"
authors = ["Joanna Zou", "Spencer Wyant", "and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
