name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - uses: julia-actions/cache@v1
      - name: add CESMIX registry
        run: |
          julia -e '
            using Pkg
            Pkg.Registry.add("General")
            Pkg.Registry.add(RegistrySpec(url = "https://github.com/cesmix-mit/CESMIX.git"))
            Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaMolSim/MolSim.git"))
            Pkg.Registry.add(RegistrySpec(url = "https://github.com/ACEsuit/ACEregistry"))
          '
        shell: bash
      - name: Install dependencies
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.add(; url = "https://github.com/joannajzou/ActiveSubspaces.jl")
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
          '
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
